// src/sidepanel/components/ChatMessage.vue
<template>
  <div class="flex items-start gap-2.5">
    <!-- 提供者头像 -->
    <div
      class="flex-shrink-0 w-7 h-7 rounded-full flex items-center justify-center text-[11px] font-bold text-white select-none mt-0.5"
      :class="themeClasses.avatar">
      {{ providerName.slice(0, 2) }}
    </div>

    <div class="flex-1 min-w-0 space-y-1">
      <!-- 头部：名称 + 状态 + 原文链接 -->
      <div class="flex items-center gap-1.5 flex-wrap min-w-0">
        <span class="text-[12px] font-semibold flex-shrink-0" :class="themeClasses.text">{{ providerName }}</span>

        <span v-if="status === 'running'" class="relative flex h-2 w-2 flex-shrink-0">
          <span class="animate-ping absolute inline-flex h-full w-full rounded-full opacity-75" :class="themeClasses.ping"></span>
          <span class="relative inline-flex rounded-full h-2 w-2" :class="themeClasses.dot"></span>
        </span>
        <CheckCircle v-else-if="status === 'completed'" class="w-3 h-3 text-emerald-500 flex-shrink-0" />
        <AlertCircle v-else-if="status === 'error'" class="w-3 h-3 text-rose-500 flex-shrink-0" />

        <span v-if="operationStatus" class="text-[10px] text-amber-500 animate-pulse truncate">{{ operationStatus }}</span>
        <span v-else-if="status === 'running'" class="text-[10px] text-slate-400 animate-pulse truncate">{{ stageLabel }}</span>
        <span v-else-if="stats && status === 'completed'" class="text-[10px] text-slate-400 truncate">
          首字 {{ (stats.ttff / 1000).toFixed(1) }}s · 总耗时 {{ (stats.totalTime / 1000).toFixed(1) }}s · {{ stats.charCount.toLocaleString('zh-CN') }}字 · {{ stats.charsPerSec }}字/s
        </span>

        <a
          v-if="rawUrl && rawUrl !== 'api'"
          :href="rawUrl"
          :target="isFromHistory ? '_blank' : undefined"
          rel="noopener noreferrer"
          class="ml-auto flex-shrink-0 inline-flex items-center gap-1 rounded-full border border-slate-200 bg-white/80 px-2 py-0.5 text-[11px] font-medium text-slate-500 shadow-sm transition-colors hover:border-indigo-200 hover:bg-indigo-50/80 hover:text-indigo-600"
          @click="onOriginalClick"
          :title="isFromHistory ? '在新标签页打开对话页' : '激活已有标签或打开对话页'">
          <ExternalLink class="w-3 h-3 opacity-80" />
          <span>原文</span>
        </a>
        <span
          v-else-if="rawUrl === 'api'"
          class="ml-auto flex-shrink-0 rounded-full border border-slate-100 bg-slate-50/80 px-2 py-0.5 text-[11px] font-medium text-slate-400">
          API
        </span>
      </div>

      <!-- 消息气泡 -->
      <div class="bg-white rounded-2xl rounded-tl-sm border border-slate-200/60 shadow-sm px-4 py-3 text-[13.5px]">
        <!-- 思考内容块 -->
        <template v-if="isDeepThinkingEnabled">
          <div v-if="thinkResponse" class="mb-3">
            <button
              @click="isThinkBlockOpen = !isThinkBlockOpen"
              class="flex items-center gap-1.5 text-[11px] text-slate-400 hover:text-slate-600 transition-colors mb-1">
              <ChevronRight class="w-3 h-3 transition-transform duration-200" :class="{ 'rotate-90': isThinkBlockOpen }" />
              <span>思考过程</span>
              <span
                v-if="stage === 'thinking' && status === 'running'"
                class="inline-block w-1 h-2.5 ml-0.5 bg-slate-400 animate-pulse align-middle">
              </span>
            </button>
            <div
              v-show="isThinkBlockOpen"
              class="pl-3 border-l border-slate-200 text-slate-500 leading-6 whitespace-pre-wrap text-[12px] break-words max-h-[200px] overflow-y-auto">
              {{ thinkResponse }}
            </div>
          </div>
          <div
            v-else-if="stage === 'thinking' && status === 'running'"
            class="mb-2 text-[11px] text-slate-400 italic flex items-center gap-1">
            正在思考...
            <span class="inline-block w-1 h-2.5 bg-slate-400 animate-pulse align-middle"></span>
          </div>
        </template>

        <!-- 正式回复 -->
        <div
          class="response-content text-slate-700 prose prose-sm max-w-none leading-7 break-words"
          :class="themeClasses.prose">
          <span v-html="renderedContent"></span>
          <span
            v-if="status === 'running' && stage === 'responding'"
            class="inline-block w-1.5 h-3.5 ml-0.5 animate-pulse align-middle"
            :class="themeClasses.dot">
          </span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { CheckCircle, AlertCircle, ExternalLink, ChevronRight } from 'lucide-vue-next';
import { marked } from 'marked';
import sanitizeHtml from 'sanitize-html';

type ProviderStats = {
  ttff: number;
  totalTime: number;
  charCount: number;
  charsPerSec: number;
};

const props = defineProps<{
  providerId: string;
  providerName: string;
  themeColor: 'blue' | 'amber' | 'emerald' | 'violet' | 'teal';
  status: 'idle' | 'running' | 'completed' | 'error';
  stage: 'connecting' | 'thinking' | 'responding';
  response: string;
  thinkResponse?: string;
  operationStatus?: string;
  rawUrl?: string;
  isFromHistory?: boolean;
  isDeepThinkingEnabled?: boolean;
  stats?: ProviderStats | null;
}>();

const isThinkBlockOpen = ref(true);

const stageLabels: Record<string, string> = {
  connecting: '等待连接网页端...',
  thinking: '已连接 · 正在思考...',
  responding: '正在输出...',
};

const themeClassMap = {
  blue: { ping: 'bg-blue-400', dot: 'bg-blue-500', text: 'text-blue-600', prose: 'prose-blue', avatar: 'bg-blue-500' },
  amber: { ping: 'bg-amber-400', dot: 'bg-amber-500', text: 'text-amber-600', prose: 'prose-amber', avatar: 'bg-amber-500' },
  emerald: { ping: 'bg-emerald-400', dot: 'bg-emerald-500', text: 'text-emerald-600', prose: 'prose-emerald', avatar: 'bg-emerald-500' },
  violet: { ping: 'bg-violet-400', dot: 'bg-violet-500', text: 'text-violet-600', prose: 'prose-violet', avatar: 'bg-violet-500' },
  teal: { ping: 'bg-teal-400', dot: 'bg-teal-500', text: 'text-teal-600', prose: 'prose-teal', avatar: 'bg-teal-500' },
} as const;

const stageLabel = computed(() => stageLabels[props.stage] || stageLabels.connecting);
const themeClasses = computed(() => themeClassMap[props.themeColor] || themeClassMap.blue);

const renderedContent = computed(() => {
  if (props.response) return renderMarkdown(props.response);
  if (props.status === 'running') return props.stage === 'responding' ? '' : stageLabel.value;
  if (props.status === 'error') return '执行失败，请查看上面的错误信息。';
  if (props.status === 'completed') return '本轮未收到可展示内容。';
  return '等待开始...';
});

function onOriginalClick(e: MouseEvent) {
  if (props.isFromHistory) return;
  e.preventDefault();
  if (props.rawUrl && typeof chrome !== 'undefined' && chrome.tabs) {
    activateOrOpenTab(props.rawUrl);
  }
}

function activateOrOpenTab(url: string) {
  try {
    const u = new URL(url);
    const pattern = u.origin + '/*';
    chrome.tabs.query({ url: pattern }, (tabs) => {
      const tab = tabs.find((t) => t.url === url);
      if (tab?.id != null) {
        chrome.tabs.update(tab.id, { active: true });
        if (tab.windowId != null) {
          chrome.windows.update(tab.windowId, { focused: true });
        }
      } else {
        chrome.tabs.create({ url });
      }
    });
  } catch {
    chrome.tabs.create({ url });
  }
}

const renderMarkdown = (text: string) => {
  if (!text) return '';
  const html = marked.parse(text);
  return sanitizeHtml(html as string, {
    allowedTags: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p', 'ul', 'ol', 'li', 'strong', 'em', 'code', 'pre', 'blockquote', 'a', 'br', 'hr', 'table', 'thead', 'tbody', 'tr', 'th', 'td'],
    allowedAttributes: { 'a': ['href', 'target', 'rel'] },
    transformTags: {
      'a': (tagName: string, attribs: Record<string, string>) => ({
        tagName: 'a',
        attribs: { ...attribs, target: '_blank', rel: 'noopener noreferrer' }
      })
    }
  });
};
</script>

<style scoped>
.response-content {
  font-family: "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei UI", "Microsoft YaHei", "Segoe UI", system-ui, -apple-system, BlinkMacSystemFont, sans-serif;
  font-size: 13.5px;
}

.response-content :deep(p),
.response-content :deep(ul),
.response-content :deep(ol),
.response-content :deep(blockquote) {
  margin-top: 0.7rem;
  margin-bottom: 0.7rem;
}

.response-content :deep(h1),
.response-content :deep(h2),
.response-content :deep(h3) {
  margin-top: 1rem;
  margin-bottom: 0.6rem;
  line-height: 1.45;
}

.response-content :deep(li) {
  margin: 0.3rem 0;
}

.response-content :deep(code) {
  font-family: ui-monospace, SFMono-Regular, "SF Mono", Consolas, "Liberation Mono", monospace;
  font-size: 0.9em;
}

.overflow-y-auto::-webkit-scrollbar {
  width: 4px;
}

.overflow-y-auto::-webkit-scrollbar-track {
  background: transparent;
}

.overflow-y-auto::-webkit-scrollbar-thumb {
  background: #cbd5e1;
  border-radius: 4px;
}
</style>

// src/sidepanel/components/ChatMessage.tsx
import { useState, useMemo } from 'react';
import { CheckCircle, AlertCircle, ExternalLink, ChevronRight } from 'lucide-react';
import { DeepSeek, Doubao, Qwen, LongCat, Yuanbao } from '@lobehub/icons';
import { renderMarkdown } from '../utils/renderMarkdown';
import type { ProviderStats, ProviderStatus, StageType, ThemeColor } from '../types';

const iconMap: Record<string, { Color?: React.ComponentType<{ size?: number | string; className?: string }> }> = {
  deepseek: DeepSeek,
  doubao: Doubao,
  qianwen: Qwen,
  longcat: LongCat,
  yuanbao: Yuanbao,
};

const STAGE_LABELS: Record<string, string> = {
  connecting: '等待连接网页端...',
  thinking: '已连接 · 正在思考...',
  responding: '正在输出...',
};

const THEME_CLASS_MAP: Record<
  ThemeColor,
  { ping: string; dot: string; text: string; prose: string; avatar: string }
> = {
  blue: { ping: 'bg-blue-400', dot: 'bg-blue-500', text: 'text-blue-600', prose: 'prose-blue', avatar: 'bg-blue-500' },
  amber: {
    ping: 'bg-amber-400',
    dot: 'bg-amber-500',
    text: 'text-amber-600',
    prose: 'prose-amber',
    avatar: 'bg-amber-500',
  },
  emerald: {
    ping: 'bg-emerald-400',
    dot: 'bg-emerald-500',
    text: 'text-emerald-600',
    prose: 'prose-emerald',
    avatar: 'bg-emerald-500',
  },
  violet: {
    ping: 'bg-violet-400',
    dot: 'bg-violet-500',
    text: 'text-violet-600',
    prose: 'prose-violet',
    avatar: 'bg-violet-500',
  },
  teal: { ping: 'bg-teal-400', dot: 'bg-teal-500', text: 'text-teal-600', prose: 'prose-teal', avatar: 'bg-teal-500' },
};

export interface ChatMessageProps {
  providerId: string;
  providerName: string;
  themeColor: ThemeColor;
  status: ProviderStatus;
  stage: StageType;
  response: string;
  thinkResponse?: string;
  operationStatus?: string;
  rawUrl?: string;
  isFromHistory?: boolean;
  isDeepThinkingEnabled?: boolean;
  stats?: ProviderStats | null;
}

function activateOrOpenTab(url: string) {
  try {
    const u = new URL(url);
    const pattern = u.origin + '/*';
    chrome.tabs.query({ url: pattern }, (tabs) => {
      const tab = tabs.find((t) => t.url === url);
      if (tab?.id != null) {
        chrome.tabs.update(tab.id, { active: true });
        if (tab.windowId != null) {
          chrome.windows.update(tab.windowId, { focused: true });
        }
      } else {
        chrome.tabs.create({ url });
      }
    });
  } catch {
    chrome.tabs.create({ url });
  }
}

export default function ChatMessage({
  providerId,
  providerName,
  themeColor,
  status,
  stage,
  response,
  thinkResponse,
  operationStatus,
  rawUrl,
  isFromHistory = false,
  isDeepThinkingEnabled = false,
  stats,
}: ChatMessageProps) {
  const [isThinkBlockOpen, setIsThinkBlockOpen] = useState(true);

  const themeClasses = THEME_CLASS_MAP[themeColor] ?? THEME_CLASS_MAP.blue;
  const stageLabel = STAGE_LABELS[stage] ?? STAGE_LABELS.connecting;
  const Icon = iconMap[providerId];

  const renderedContent = useMemo(() => {
    if (response) return renderMarkdown(response);
    if (status === 'running') return stage === 'responding' ? '' : stageLabel;
    if (status === 'error') return '执行失败，请查看上面的错误信息。';
    if (status === 'completed') return '本轮未收到可展示内容。';
    return '等待开始...';
  }, [response, status, stage, stageLabel]);

  const handleOriginalClick = (e: React.MouseEvent<HTMLAnchorElement>) => {
    if (isFromHistory) return;
    e.preventDefault();
    if (rawUrl && typeof chrome !== 'undefined' && chrome.tabs) {
      activateOrOpenTab(rawUrl);
    }
  };

  return (
    <div className="flex items-start gap-2.5">
      {/* 提供者头像 - 使用 @lobehub/icons .Color 图标 */}
      <div
        className={`flex-shrink-0 w-7 h-7 rounded-full flex items-center justify-center text-white select-none mt-0.5 ${themeClasses.avatar}`}
      >
        {Icon?.Color ? (
          <Icon.Color size={14} className="text-white" />
        ) : (
          <span className="text-[11px] font-bold">{providerName.slice(0, 2)}</span>
        )}
      </div>

      <div className="flex-1 min-w-0 space-y-1">
        {/* 头部：名称 + 状态 + 原文链接 */}
        <div className="flex items-center gap-1.5 flex-wrap min-w-0">
          <span className={`text-[12px] font-semibold flex-shrink-0 ${themeClasses.text}`}>{providerName}</span>

          {status === 'running' && (
            <span className="relative flex h-2 w-2 flex-shrink-0">
              <span className={`animate-ping absolute inline-flex h-full w-full rounded-full opacity-75 ${themeClasses.ping}`} />
              <span className={`relative inline-flex rounded-full h-2 w-2 ${themeClasses.dot}`} />
            </span>
          )}
          {status === 'completed' && <CheckCircle className="w-3 h-3 text-emerald-500 flex-shrink-0" />}
          {status === 'error' && <AlertCircle className="w-3 h-3 text-rose-500 flex-shrink-0" />}

          {operationStatus && (
            <span className="text-[10px] text-amber-500 animate-pulse truncate">{operationStatus}</span>
          )}
          {!operationStatus && status === 'running' && (
            <span className="text-[10px] text-slate-400 animate-pulse truncate">{stageLabel}</span>
          )}
          {!operationStatus && stats && status === 'completed' && (
            <span className="text-[10px] text-slate-400 truncate">
              首字 {(stats.ttff / 1000).toFixed(1)}s · 总耗时 {(stats.totalTime / 1000).toFixed(1)}s ·{' '}
              {stats.charCount.toLocaleString('zh-CN')}字 · {stats.charsPerSec}字/s
            </span>
          )}

          {rawUrl && rawUrl !== 'api' && (
            <a
              href={rawUrl}
              target={isFromHistory ? '_blank' : undefined}
              rel="noopener noreferrer"
              className="ml-auto flex-shrink-0 inline-flex items-center gap-1 rounded-full border border-slate-200 bg-white/80 px-2 py-0.5 text-[11px] font-medium text-slate-500 shadow-sm transition-colors hover:border-indigo-200 hover:bg-indigo-50/80 hover:text-indigo-600"
              onClick={handleOriginalClick}
              title={isFromHistory ? '在新标签页打开对话页' : '激活已有标签或打开对话页'}
            >
              <ExternalLink className="w-3 h-3 opacity-80" />
              <span>原文</span>
            </a>
          )}
          {rawUrl === 'api' && (
            <span className="ml-auto flex-shrink-0 rounded-full border border-slate-100 bg-slate-50/80 px-2 py-0.5 text-[11px] font-medium text-slate-400">
              API
            </span>
          )}
        </div>

        {/* 消息气泡 */}
        <div className="bg-white rounded-2xl rounded-tl-sm border border-slate-200/60 shadow-sm px-4 py-3 text-[13.5px]">
          {/* 思考内容块 */}
          {isDeepThinkingEnabled && (
            <>
              {thinkResponse ? (
                <div className="mb-3">
                  <button
                    type="button"
                    onClick={() => setIsThinkBlockOpen(!isThinkBlockOpen)}
                    className="flex items-center gap-1.5 text-[11px] text-slate-400 hover:text-slate-600 transition-colors mb-1"
                  >
                    <ChevronRight
                      className={`w-3 h-3 transition-transform duration-200 ${isThinkBlockOpen ? 'rotate-90' : ''}`}
                    />
                    <span>思考过程</span>
                    {stage === 'thinking' && status === 'running' && (
                      <span className="inline-block w-1 h-2.5 ml-0.5 bg-slate-400 animate-pulse align-middle" />
                    )}
                  </button>
                  {isThinkBlockOpen && (
                    <div className="response-scroll pl-3 border-l border-slate-200 text-slate-500 leading-6 whitespace-pre-wrap text-[12px] break-words max-h-[200px] overflow-y-auto">
                      {thinkResponse}
                    </div>
                  )}
                </div>
              ) : (
                stage === 'thinking' &&
                status === 'running' && (
                  <div className="mb-2 text-[11px] text-slate-400 italic flex items-center gap-1">
                    正在思考...
                    <span className="inline-block w-1 h-2.5 bg-slate-400 animate-pulse align-middle" />
                  </div>
                )
              )}
            </>
          )}

          {/* 正式回复 */}
          <div
            className={`response-content text-slate-700 prose prose-sm max-w-none leading-7 break-words ${themeClasses.prose}`}
          >
            <span dangerouslySetInnerHTML={{ __html: renderedContent }} />
            {status === 'running' && stage === 'responding' && (
              <span className={`inline-block w-1.5 h-3.5 ml-0.5 animate-pulse align-middle ${themeClasses.dot}`} />
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
