// src/sidepanel/components/ProviderCollapse.tsx
import { useState, useEffect, useMemo } from 'react';
import { CheckCircle, AlertCircle, ExternalLink, ChevronDown, ChevronRight } from 'lucide-react';
import { DeepSeek, Doubao, Qwen, LongCat, Yuanbao } from '@lobehub/icons';
import { renderMarkdown } from '../utils/renderMarkdown';
import type { ProviderStats, ProviderStatus, StageType, ThemeColor } from '../types';

const iconMap: Record<string, { Color?: React.ComponentType<{ size?: number | string; className?: string }> }> = {
  deepseek: DeepSeek,
  doubao: Doubao,
  qianwen: Qwen,
  longcat: LongCat,
  yuanbao: Yuanbao,
};

const STAGE_LABELS: Record<string, string> = {
  connecting: '等待连接网页端...',
  thinking: '已连接 · 正在思考...',
  responding: '正在输出...',
};

const THEME_CLASS_MAP: Record<ThemeColor, { ping: string; dot: string; text: string; prose: string }> = {
  blue: { ping: 'bg-blue-400', dot: 'bg-blue-500', text: 'text-blue-600', prose: 'prose-blue' },
  amber: { ping: 'bg-amber-400', dot: 'bg-amber-500', text: 'text-amber-600', prose: 'prose-amber' },
  emerald: {
    ping: 'bg-emerald-400',
    dot: 'bg-emerald-500',
    text: 'text-emerald-600',
    prose: 'prose-emerald',
  },
  violet: { ping: 'bg-violet-400', dot: 'bg-violet-500', text: 'text-violet-600', prose: 'prose-violet' },
  teal: { ping: 'bg-teal-400', dot: 'bg-teal-500', text: 'text-teal-600', prose: 'prose-teal' },
};

export interface ProviderCollapseProps {
  providerId: string;
  providerName: string;
  themeColor: ThemeColor;
  status: ProviderStatus;
  stage: StageType;
  response: string;
  thinkResponse?: string;
  operationStatus?: string;
  rawUrl?: string;
  isFromHistory?: boolean;
  isDeepThinkingEnabled?: boolean;
  defaultOpen?: boolean;
  stats?: ProviderStats | null;
}

function activateOrOpenTab(url: string) {
  try {
    const u = new URL(url);
    const pattern = u.origin + '/*';
    chrome.tabs.query({ url: pattern }, (tabs) => {
      const tab = tabs.find((t) => t.url === url);
      if (tab?.id != null) {
        chrome.tabs.update(tab.id, { active: true });
        if (tab.windowId != null) {
          chrome.windows.update(tab.windowId, { focused: true });
        }
      } else {
        chrome.tabs.create({ url });
      }
    });
  } catch {
    chrome.tabs.create({ url });
  }
}

export default function ProviderCollapse({
  providerId,
  providerName,
  themeColor,
  status,
  stage,
  response,
  thinkResponse,
  operationStatus,
  rawUrl,
  isFromHistory = false,
  isDeepThinkingEnabled = false,
  defaultOpen = true,
  stats,
}: ProviderCollapseProps) {
  const [isOpen, setIsOpen] = useState(defaultOpen);
  const [isThinkBlockOpen, setIsThinkBlockOpen] = useState(true);

  useEffect(() => {
    setIsOpen(defaultOpen ?? true);
  }, [defaultOpen]);

  const themeClasses = THEME_CLASS_MAP[themeColor] ?? THEME_CLASS_MAP.blue;
  const stageLabel = STAGE_LABELS[stage] ?? STAGE_LABELS.connecting;
  const Icon = iconMap[providerId];

  const statusText = useMemo(() => {
    if (status === 'running') return '正在输出...';
    if (status === 'completed') return '(已完成)';
    if (status === 'error') return '(出错)';
    return '(待开始)';
  }, [status]);

  const renderedContent = useMemo(() => {
    if (response) return renderMarkdown(response);
    if (status === 'running') return stage === 'responding' ? '' : stageLabel;
    if (status === 'error') return '执行失败，请查看上面的错误信息。';
    if (status === 'completed') return '本轮未收到可展示内容。';
    return '等待开始...';
  }, [response, status, stage, stageLabel]);

  const handleOriginalClick = (e: React.MouseEvent<HTMLAnchorElement>) => {
    if (isFromHistory) return;
    e.preventDefault();
    e.stopPropagation();
    if (rawUrl && typeof chrome !== 'undefined' && chrome.tabs) {
      activateOrOpenTab(rawUrl);
    }
  };

  return (
    <div className="bg-white rounded-xl border border-slate-200/60 shadow-sm overflow-hidden transition-all duration-300">
      <button
        type="button"
        onClick={() => setIsOpen(!isOpen)}
        className="w-full flex items-center justify-between p-3 bg-slate-50/50 hover:bg-slate-50 transition-colors"
      >
        <div className="flex items-center gap-2.5 min-w-0">
          {status === 'running' && (
            <span className="relative flex h-3 w-3 ml-1 flex-shrink-0">
              <span className={`animate-ping absolute inline-flex h-full w-full rounded-full opacity-75 ${themeClasses.ping}`} />
              <span className={`relative inline-flex rounded-full h-3 w-3 ${themeClasses.dot}`} />
            </span>
          )}
          {status === 'completed' && (
            <span className="text-emerald-500 ml-1 flex-shrink-0">
              <CheckCircle className="w-3.5 h-3.5" />
            </span>
          )}
          {status === 'error' && (
            <span className="text-rose-500 ml-1 flex-shrink-0">
              <AlertCircle className="w-3.5 h-3.5" />
            </span>
          )}
          {status === 'idle' && (
            <span className="text-slate-300 ml-1 flex-shrink-0">
              <span className="inline-flex rounded-full h-3 w-3 bg-slate-300" />
            </span>
          )}

          {Icon?.Color && (
            <span className="ml-0.5 flex-shrink-0">
              <Icon.Color size={14} />
            </span>
          )}
          <span className={`text-[12px] font-medium flex-shrink-0 ${themeClasses.text}`}>
            {providerName} {statusText}
          </span>
          {operationStatus && (
            <span className="text-[10px] font-normal text-amber-500 animate-pulse truncate">{operationStatus}</span>
          )}
          {!operationStatus && status === 'running' && (
            <span className="text-[10px] font-normal text-slate-400 animate-pulse truncate">{stageLabel}</span>
          )}
          {!operationStatus && stats && status === 'completed' && (
            <span className="text-[10px] font-normal text-slate-400 truncate">
              首字 {(stats.ttff / 1000).toFixed(1)}s · 总耗时 {(stats.totalTime / 1000).toFixed(1)}s ·{' '}
              {stats.charCount.toLocaleString('zh-CN')}字 · {stats.charsPerSec}字/s
            </span>
          )}
        </div>

        <div className="flex items-center gap-2 flex-shrink-0">
          {rawUrl && rawUrl !== 'api' && (
            <a
              href={rawUrl}
              target={isFromHistory ? '_blank' : undefined}
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1 rounded-full border border-slate-200 bg-white/80 px-2 py-1 text-[11px] font-medium text-slate-500 shadow-sm transition-colors hover:border-indigo-200 hover:bg-indigo-50/80 hover:text-indigo-600"
              onClick={handleOriginalClick}
              title={isFromHistory ? '在新标签页打开对话页' : '激活已有标签或打开对话页'}
            >
              <ExternalLink className="w-3 h-3 opacity-80" />
              <span>原文</span>
            </a>
          )}
          {rawUrl === 'api' && (
            <span className="rounded-full border border-slate-100 bg-slate-50/80 px-2 py-0.5 text-[11px] font-medium text-slate-400">
              API
            </span>
          )}
          <ChevronDown className={`w-4 h-4 text-slate-400 transition-transform duration-200 ${isOpen ? 'rotate-180' : ''}`} />
        </div>
      </button>

      {isOpen && (
        <div className="p-4 border-t border-slate-100 bg-white max-h-[380px] overflow-y-auto text-[13px] response-scroll">
          {/* 思考内容折叠块 */}
          {isDeepThinkingEnabled && (
            <>
              {thinkResponse ? (
                <div className="mb-2">
                  <button
                    type="button"
                    onClick={() => setIsThinkBlockOpen(!isThinkBlockOpen)}
                    className="flex items-center gap-1.5 text-[11px] text-slate-400 hover:text-slate-600 transition-colors mb-1"
                  >
                    <ChevronRight
                      className={`w-3 h-3 transition-transform duration-200 ${isThinkBlockOpen ? 'rotate-90' : ''}`}
                    />
                    <span>思考过程</span>
                    {stage === 'thinking' && status === 'running' && (
                      <span className="inline-block w-1 h-2.5 ml-0.5 bg-slate-400 animate-pulse align-middle" />
                    )}
                  </button>
                  {isThinkBlockOpen && (
                    <div className="pl-3 border-l border-slate-200 text-slate-500 leading-6 whitespace-pre-wrap text-[12px] break-words">
                      {thinkResponse}
                    </div>
                  )}
                </div>
              ) : (
                stage === 'thinking' &&
                status === 'running' && (
                  <div className="mb-2 text-[11px] text-slate-400 italic flex items-center gap-1">
                    正在思考...
                    <span className="inline-block w-1 h-2.5 bg-slate-400 animate-pulse align-middle" />
                  </div>
                )
              )}
            </>
          )}

          {/* 正式回复 */}
          <div className={`response-content text-slate-700 prose prose-sm max-w-none text-[13.5px] leading-7 break-words ${themeClasses.prose}`}>
            <span dangerouslySetInnerHTML={{ __html: renderedContent }} />
            {status === 'running' && stage === 'responding' && (
              <span className={`inline-block w-1.5 h-3.5 ml-0.5 animate-pulse align-middle ${themeClasses.dot}`} />
            )}
          </div>
        </div>
      )}
    </div>
  );
}

// src/sidepanel/components/ProviderCollapse.vue
<template>
  <div class="bg-white rounded-xl border border-slate-200/60 shadow-sm overflow-hidden transition-all duration-300">
    <button @click="isOpen = !isOpen"
      class="w-full flex items-center justify-between p-3 bg-slate-50/50 hover:bg-slate-50 transition-colors">
      <div class="flex items-center gap-2.5 min-w-0">
        <span v-if="status === 'running'" class="relative flex h-3 w-3 ml-1 flex-shrink-0">
          <span
            class="animate-ping absolute inline-flex h-full w-full rounded-full opacity-75"
            :class="themeClasses.ping"></span>
          <span class="relative inline-flex rounded-full h-3 w-3" :class="themeClasses.dot"></span>
        </span>
        <span v-else-if="status === 'completed'" class="text-emerald-500 ml-1 flex-shrink-0">
          <CheckCircle class="w-3.5 h-3.5" />
        </span>
        <span v-else-if="status === 'error'" class="text-rose-500 ml-1 flex-shrink-0">
          <AlertCircle class="w-3.5 h-3.5" />
        </span>
        <span v-else class="text-slate-300 ml-1 flex-shrink-0">
          <span class="inline-flex rounded-full h-3 w-3 bg-slate-300"></span>
        </span>
        <span class="text-[12px] font-medium flex-shrink-0" :class="themeClasses.text">
          {{ providerName }} {{ statusText }}
        </span>
        <span v-if="operationStatus"
          class="text-[10px] font-normal text-amber-500 animate-pulse truncate">{{ operationStatus }}</span>
        <span v-else-if="status === 'running'"
          class="text-[10px] font-normal text-slate-400 animate-pulse truncate">{{ stageLabel }}</span>
        <span v-else-if="stats && status === 'completed'"
          class="text-[10px] font-normal text-slate-400 truncate">
          首字 {{ (stats.ttff / 1000).toFixed(1) }}s · 总耗时 {{ (stats.totalTime / 1000).toFixed(1) }}s · {{ stats.charCount.toLocaleString('zh-CN') }}字 · {{ stats.charsPerSec }}字/s
        </span>
      </div>
      <div class="flex items-center gap-2 flex-shrink-0">
        <a
          v-if="rawUrl && rawUrl !== 'api'"
          :href="rawUrl"
          :target="isFromHistory ? '_blank' : undefined"
          rel="noopener noreferrer"
          class="inline-flex items-center gap-1 rounded-full border border-slate-200 bg-white/80 px-2 py-1 text-[11px] font-medium text-slate-500 shadow-sm transition-colors hover:border-indigo-200 hover:bg-indigo-50/80 hover:text-indigo-600"
          @click.stop="onOriginalClick"
          :title="isFromHistory ? '在新标签页打开对话页' : '激活已有标签或打开对话页'">
          <ExternalLink class="w-3 h-3 opacity-80" />
          <span>原文</span>
        </a>
        <span
          v-else-if="rawUrl === 'api'"
          class="rounded-full border border-slate-100 bg-slate-50/80 px-2 py-0.5 text-[11px] font-medium text-slate-400">
          API
        </span>
        <ChevronDown class="w-4 h-4 text-slate-400 transition-transform duration-200" :class="{ 'rotate-180': isOpen }" />
      </div>
    </button>

    <div v-show="isOpen"
      class="p-4 border-t border-slate-100 bg-white max-h-[380px] overflow-y-auto text-[13px]">
      <!-- 思考内容折叠块 (启用深度思考时显示) -->
      <template v-if="isDeepThinkingEnabled">
        <div v-if="thinkResponse" class="mb-2">
          <button @click="isThinkBlockOpen = !isThinkBlockOpen"
            class="flex items-center gap-1.5 text-[11px] text-slate-400 hover:text-slate-600 transition-colors mb-1">
            <ChevronRight class="w-3 h-3 transition-transform duration-200" :class="{ 'rotate-90': isThinkBlockOpen }" />
            <span>思考过程</span>
            <span v-if="stage === 'thinking' && status === 'running'"
              class="inline-block w-1 h-2.5 ml-0.5 bg-slate-400 animate-pulse align-middle"></span>
          </button>
          <div v-show="isThinkBlockOpen"
            class="pl-3 border-l border-slate-200 text-slate-500 leading-6 whitespace-pre-wrap text-[12px] break-words">
            {{ thinkResponse }}
          </div>
        </div>
        <div v-else-if="stage === 'thinking' && status === 'running'"
          class="mb-2 text-[11px] text-slate-400 italic flex items-center gap-1">
          正在思考...
          <span class="inline-block w-1 h-2.5 bg-slate-400 animate-pulse align-middle"></span>
        </div>
      </template>

      <!-- 正式回复 -->
      <div class="response-content text-slate-700 prose prose-sm max-w-none text-[13.5px] leading-7 break-words"
        :class="themeClasses.prose">
        <span v-html="renderedContent"></span>
        <span v-if="status === 'running' && stage === 'responding'"
          class="inline-block w-1.5 h-3.5 ml-0.5 animate-pulse align-middle"
          :class="themeClasses.dot"></span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { CheckCircle, AlertCircle, ExternalLink, ChevronDown, ChevronRight } from 'lucide-vue-next';
import { marked } from 'marked';
import sanitizeHtml from 'sanitize-html';

type ProviderStats = {
  ttff: number;
  totalTime: number;
  charCount: number;
  charsPerSec: number;
};

const props = defineProps<{
  providerId: string;
  providerName: string;
  themeColor: 'blue' | 'amber' | 'emerald' | 'violet' | 'teal';
  status: 'idle' | 'running' | 'completed' | 'error';
  stage: 'connecting' | 'thinking' | 'responding';
  response: string;
  thinkResponse?: string;
  operationStatus?: string;
  rawUrl?: string;
  /** 是否来自历史会话：历史会话点原文打开新标签，新会话则激活已有 tab */
  isFromHistory?: boolean;
  isDeepThinkingEnabled?: boolean;
  defaultOpen?: boolean;
  stats?: ProviderStats | null;
}>();

const isOpen = ref(props.defaultOpen ?? true);
const isThinkBlockOpen = ref(true);

const stageLabels: Record<string, string> = {
  connecting: '等待连接网页端...',
  thinking: '已连接 · 正在思考...',
  responding: '正在输出...',
};

const themeClassMap = {
  blue: {
    ping: 'bg-blue-400',
    dot: 'bg-blue-500',
    text: 'text-blue-600',
    prose: 'prose-blue',
  },
  amber: {
    ping: 'bg-amber-400',
    dot: 'bg-amber-500',
    text: 'text-amber-600',
    prose: 'prose-amber',
  },
  emerald: {
    ping: 'bg-emerald-400',
    dot: 'bg-emerald-500',
    text: 'text-emerald-600',
    prose: 'prose-emerald',
  },
  violet: {
    ping: 'bg-violet-400',
    dot: 'bg-violet-500',
    text: 'text-violet-600',
    prose: 'prose-violet',
  },
  teal: {
    ping: 'bg-teal-400',
    dot: 'bg-teal-500',
    text: 'text-teal-600',
    prose: 'prose-teal',
  },
} as const;

const stageLabel = computed(() => stageLabels[props.stage] || stageLabels.connecting);
const themeClasses = computed(() => themeClassMap[props.themeColor] || themeClassMap.blue);
const statusText = computed(() => {
  if (props.status === 'running') return '正在输出...';
  if (props.status === 'completed') return '(已完成)';
  if (props.status === 'error') return '(出错)';
  return '(待开始)';
});
const renderedContent = computed(() => {
  if (props.response) return renderMarkdown(props.response);
  if (props.status === 'running') return props.stage === 'responding' ? '' : stageLabel.value;
  if (props.status === 'error') return '执行失败，请查看上面的错误信息。';
  if (props.status === 'completed') return '本轮未收到可展示内容。';
  return '等待开始...';
});

watch(() => props.defaultOpen, (value) => {
  isOpen.value = value ?? true;
});

function onOriginalClick(e: MouseEvent) {
  if (props.isFromHistory) return; // 历史会话：不拦截，用 href + target="_blank" 打开新标签
  e.preventDefault();
  if (props.rawUrl && typeof chrome !== 'undefined' && chrome.tabs) {
    activateOrOpenTab(props.rawUrl);
  }
}

function activateOrOpenTab(url: string) {
  try {
    const u = new URL(url);
    const pattern = u.origin + '/*';
    chrome.tabs.query({ url: pattern }, (tabs) => {
      const tab = tabs.find((t) => t.url === url);
      if (tab?.id != null) {
        chrome.tabs.update(tab.id, { active: true });
        if (tab.windowId != null) {
          chrome.windows.update(tab.windowId, { focused: true });
        }
      } else {
        chrome.tabs.create({ url });
      }
    });
  } catch {
    chrome.tabs.create({ url });
  }
}

// Markdown 渲染方法
const renderMarkdown = (text: string) => {
  if (!text) return '';
  const html = marked.parse(text);
  return sanitizeHtml(html as string, {
    allowedTags: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p', 'ul', 'ol', 'li', 'strong', 'em', 'code', 'pre', 'blockquote', 'a', 'br', 'hr', 'table', 'thead', 'tbody', 'tr', 'th', 'td'],
    allowedAttributes: {
      'a': ['href', 'target', 'rel']
    },
    transformTags: {
      'a': (tagName: string, attribs: Record<string, string>) => {
        return {
          tagName: 'a',
          attribs: {
            ...attribs,
            target: '_blank',
            rel: 'noopener noreferrer'
          }
        };
      }
    }
  });
};
</script>

<style scoped>
.overflow-y-auto::-webkit-scrollbar {
  width: 4px;
}

.overflow-y-auto::-webkit-scrollbar-track {
  background: transparent;
}

.overflow-y-auto::-webkit-scrollbar-thumb {
  background: #cbd5e1;
  border-radius: 4px;
}

.response-content {
  font-family: "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei UI", "Microsoft YaHei", "Segoe UI", system-ui, -apple-system, BlinkMacSystemFont, sans-serif;
}

.response-content :deep(p),
.response-content :deep(ul),
.response-content :deep(ol),
.response-content :deep(blockquote) {
  margin-top: 0.7rem;
  margin-bottom: 0.7rem;
}

.response-content :deep(h1),
.response-content :deep(h2),
.response-content :deep(h3) {
  margin-top: 1rem;
  margin-bottom: 0.6rem;
  line-height: 1.45;
}

.response-content :deep(li) {
  margin: 0.3rem 0;
}

.response-content :deep(code) {
  font-family: ui-monospace, SFMono-Regular, "SF Mono", Consolas, "Liberation Mono", monospace;
  font-size: 0.9em;
}
</style>
